auth:
  adminUser: admin
  adminPassword: adminpassword
service:
  type: LoadBalancer
postgresql:
  enabled: true
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 256m
    memory: 512Mi
